@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mastermarisa.kaleidoscopecookery_automation.arm.type;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;