@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mastermarisa.kaleidoscopecookery_automation.utils;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;